### ISSUE TITLE
Bug in RSAUtils - Swift 3

### ISSUE THREAD

**Issue by victorpintot8** [Kushki/kushki-ios#1]
Hi, i just added Kushki 2.0.2 via Cocoapods, installed the Pod and build my project but this error appeared.
<img width="758" alt="captura de pantalla 2017-08-14 a la s 09 38 50" src="https://user-images.githubusercontent.com/2744914/29276497-6b59ccf8-80d4-11e7-8cf1-46d26b72f0a3.png">

It happens to be a common bug related to RSAUtils library, Swift 3 and Xcode 9. The solution was to replace the old code with this one:

`var queryFilter = [String : Any]()
            queryFilter[String(kSecClass)] = kSecClassKey
            queryFilter[String(kSecAttrKeyType)] =  kSecAttrKeyTypeRSA
            queryFilter[String(kSecAttrApplicationTag)] = tagName
            //String(kSecAttrAccessible)     : kSecAttrAccessibleWhenUnlocked,
            queryFilter[String(kSecValueData)] = privkeyData!
            queryFilter[String(kSecAttrKeyClass)] = kSecAttrKeyClassPrivate
            queryFilter[String(kSecReturnPersistentRef)] = true`

Hope it helps somebody else, thanks.

**Comment by joseSantacruz** [comment]
Hi, @victorpintot8 excellent you fix the issue, maybe could you made a pull request so everybody can have it resolved.
